services:
  app:
    build:
      context: ..
      dockerfile: docker/app.Dockerfile
    restart: unless-stopped
    depends_on:
    - db
    ports:
      - "${PORT}:${PORT}"
    environment:
      - DATABASE_URL=postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@db:${DATABASE_PORT}/${DATABASE_NAME}
      - HOST=${HOST}
      - PORT=${PORT}

  db:
    restart: unless-stopped
    image: postgres:15-alpine
    hostname: db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}

volumes:
  postgres_data:
    driver: local
